<a href="https://colab.research.google.com/github/srikanth-challa199/machine-learning-part/blob/main/machine_learning_basics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
x_train,x_test=train_test_split(dataset)
print(x_train)
print(x_test)

[3 7 8 6 2 4 9]
[0 5 1]


In [8]:
import numpy as np
from sklearn.model_selection import train_test_split
dataset=np.arange(10)
x_train,x_test=train_test_split(dataset,train_size=7,test_size=3)
print(x_train)
print(x_test)

[0 5 4 6 8 9 7]
[1 3 2]


In [ ]:
import numpy as np
from sklearn.model_selection import train_test_split
x=np.arange(20).reshape(2,10).T
y=np.arange(10)
X_train,X_test,y_train,y_test=train_test_split(x,y,train_size=7,test_size=3,random_state=0)
print(X_train)
print()
print(X_test)
print()
print(y_train)
print()
print(y_test)